// SPDX-License-Identifier: MIT
// Copyright (c) Robert Vokac and contributors
//
// The release identity generated by cmake/Version.cmake into
// <build>/generated/include/SharpRuntime/Version.hpp.
//
// Deliberately STRUCTURAL rather than an equality check against a literal release: what is worth
// pinning is that the CMake-side decision and the generated header agree, and that the string is
// built from the components the accessors report. A suite that asserted "0.1.0-alpha.1" would
// have to be edited by every version bump, and would then be asserting the edit rather than the
// agreement -- so it would pass a bump that updated the test and broke the header.
#include <gtest/gtest.h>

#include <string>
#include <string_view>

#include "SharpRuntime/Version.hpp"

namespace
{
    // The whole header is a compile-time constant folded away in every build; these
    // static_asserts pin the part of the contract no runtime EXPECT can reach, and fail the
    // BUILD rather than a test run if an accessor ever stops being usable in a constant
    // expression -- which is what a consumer's `if constexpr` version gate depends on.
    static_assert(SharpRuntime::getVersionMajor() == SHARP_RUNTIME_VERSION_MAJOR,
                  "getVersionMajor() must be usable in a constant expression");
    static_assert(SharpRuntime::getVersionMinor() == SHARP_RUNTIME_VERSION_MINOR,
                  "getVersionMinor() must be usable in a constant expression");
    static_assert(SharpRuntime::getVersionPatch() == SHARP_RUNTIME_VERSION_PATCH,
                  "getVersionPatch() must be usable in a constant expression");
    static_assert(!SharpRuntime::getVersionString().empty(),
                  "getVersionString() must be a non-empty constant expression");
    static_assert(SharpRuntime::isPreReleaseVersion()
                      == !SharpRuntime::getVersionPreRelease().empty(),
                  "isPreReleaseVersion() must be usable in a constant expression");

    TEST(SharpRuntimeVersionTest, ComponentsAreNonNegative)
    {
        EXPECT_GE(SharpRuntime::getVersionMajor(), 0);
        EXPECT_GE(SharpRuntime::getVersionMinor(), 0);
        EXPECT_GE(SharpRuntime::getVersionPatch(), 0);
    }

    TEST(SharpRuntimeVersionTest, StringStartsWithTheNumericComponents)
    {
        const std::string numeric = std::to_string(SharpRuntime::getVersionMajor()) + '.'
                                    + std::to_string(SharpRuntime::getVersionMinor()) + '.'
                                    + std::to_string(SharpRuntime::getVersionPatch());

        EXPECT_TRUE(SharpRuntime::getVersionString().starts_with(numeric))
            << SharpRuntime::getVersionString();
    }

    TEST(SharpRuntimeVersionTest, StringAppendsThePreReleaseIdentifierExactlyWhenThereIsOne)
    {
        const std::string_view version = SharpRuntime::getVersionString();
        const std::string_view preRelease = SharpRuntime::getVersionPreRelease();

        if (preRelease.empty())
        {
            EXPECT_EQ(std::string_view::npos, version.find('-')) << version;
        }
        else
        {
            EXPECT_TRUE(version.ends_with(std::string("-") + std::string(preRelease))) << version;
        }
    }

    TEST(SharpRuntimeVersionTest, IsPreReleaseVersionMatchesThePreReleaseIdentifier)
    {
        EXPECT_EQ(!SharpRuntime::getVersionPreRelease().empty(),
                  SharpRuntime::isPreReleaseVersion());
    }

    TEST(SharpRuntimeVersionTest, StringIsSemanticVersioningSpellingWithoutAVPrefixOrWhitespace)
    {
        const std::string_view version = SharpRuntime::getVersionString();

        ASSERT_FALSE(version.empty());
        EXPECT_NE('v', version.front()) << version;
        EXPECT_EQ(std::string_view::npos, version.find(' ')) << version;
        EXPECT_EQ(std::string_view::npos, version.find('\t')) << version;
    }

    TEST(SharpRuntimeVersionTest, MacrosAndAccessorsReportTheSameRelease)
    {
        EXPECT_EQ(SHARP_RUNTIME_VERSION_MAJOR, SharpRuntime::getVersionMajor());
        EXPECT_EQ(SHARP_RUNTIME_VERSION_MINOR, SharpRuntime::getVersionMinor());
        EXPECT_EQ(SHARP_RUNTIME_VERSION_PATCH, SharpRuntime::getVersionPatch());
        EXPECT_EQ(std::string_view{SHARP_RUNTIME_VERSION_PRERELEASE},
                  SharpRuntime::getVersionPreRelease());
        EXPECT_EQ(std::string_view{SHARP_RUNTIME_VERSION_STRING},
                  SharpRuntime::getVersionString());
    }
}
