#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) Robert Vokac and contributors
"""Generate the documented component catalogue from CMake module metadata."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys

from validate_module_boundaries import (
    HEADER_SUFFIXES,
    MODULE_LIST_PATH,
    REPO_ROOT,
    Module,
    _cmake_tokens,
    _extract_call_bodies,
    _parse_module,
    _parse_module_directories,
)


OUTPUT_PATH = Path("docs/ComponentCatalog.md")
COMPONENT_FIELDS = {
    "NAME",
    "TARGET",
    "TYPE",
    "SETUP",
    "ALIAS_OF",
    "INCLUDE_DIRECTORY",
    "SOURCES",
    "DEPENDENCIES",
    "PUBLIC_DEPENDENCIES",
    "PRIVATE_DEPENDENCIES",
    "TEST_SOURCES",
    "TEST_DEPENDENCIES",
}
EXTERNAL_DEPENDENCIES = {
    "IO.Compression": "ZLIB (private)",
    "IO.Compression.Zip": "vendored miniz (private)",
    "Net": "`ws2_32` on Windows (private)",
    "Security.Cryptography.Random": "`bcrypt` on Windows (private)",
    "Storage": "parent-provided SDL3 on Android (private)",
    "Xml": "vendored tinyxml2 (public)",
}


@dataclass(frozen=True)
class CompatibilityComponent:
    name: str
    owner: str
    component_type: str
    dependencies: tuple[str, ...]
    include_directory: Path


def _values(tokens: list[str], field_name: str) -> list[str]:
    if field_name not in tokens:
        return []
    index = tokens.index(field_name) + 1
    values: list[str] = []
    while index < len(tokens) and tokens[index] not in COMPONENT_FIELDS:
        values.append(tokens[index])
        index += 1
    return values


def _value(tokens: list[str], field_name: str) -> str:
    values = _values(tokens, field_name)
    return values[0] if values else ""


def _load_metadata(
    root: Path,
) -> tuple[list[Module], list[CompatibilityComponent]]:
    directories, problems = _parse_module_directories(root / MODULE_LIST_PATH)
    modules: list[Module] = []
    compatibility: list[CompatibilityComponent] = []
    for directory in directories:
        cmake_path = root / "modules" / directory / "CMakeLists.txt"
        module, module_problems = _parse_module(directory, cmake_path)
        problems.extend(module_problems)
        if module is not None:
            modules.append(module)

        text = cmake_path.read_text(encoding="utf-8")
        for body in _extract_call_bodies(
            text,
            "sharp_runtime_register_component",
        ):
            tokens = _cmake_tokens(body)
            name = _value(tokens, "NAME")
            alias_of = _value(tokens, "ALIAS_OF")
            dependencies = tuple(
                _values(tokens, "PUBLIC_DEPENDENCIES")
                or _values(tokens, "DEPENDENCIES")
            )
            if alias_of:
                component_type = f"alias of {alias_of}"
                dependencies = (alias_of,)
            else:
                component_type = "compatibility umbrella"
            compatibility.append(
                CompatibilityComponent(
                    name=name,
                    owner=directory,
                    component_type=component_type,
                    dependencies=dependencies,
                    include_directory=root / "modules" / directory / "include",
                )
            )
    if problems:
        raise ValueError("\n".join(problems))
    compatibility.append(
        CompatibilityComponent(
            name="All",
            owner="CMake aggregate",
            component_type="compatibility umbrella",
            dependencies=tuple(module.name for module in modules),
            include_directory=root / "modules" / "core" / "include",
        )
    )
    return modules, compatibility


def _representative_header(include_directory: Path) -> str:
    headers = sorted(
        path.relative_to(include_directory).as_posix()
        for path in include_directory.rglob("*")
        if path.is_file() and path.suffix in HEADER_SUFFIXES
    )
    return headers[0] if headers else "—"


def _format_items(items: tuple[str, ...] | frozenset[str]) -> str:
    return ", ".join(f"`{item}`" for item in sorted(items)) or "—"


def _render(root: Path) -> str:
    modules, compatibility = _load_metadata(root)
    edge_count = sum(len(module.all_dependencies) for module in modules)
    lines = [
        "<!-- SPDX-License-Identifier: MIT -->",
        "<!-- Copyright (c) Robert Vokac and contributors -->",
        "<!-- Generated by scripts/generate_component_catalog.py. Do not edit. -->",
        "",
        "# Generated Sharp Runtime component catalogue",
        "",
        "This file is generated from the CMake component registrations. Run",
        "`python3 scripts/generate_component_catalog.py` after changing module",
        "metadata, or use `--check` to verify that the committed catalogue is current.",
        "",
        f"The graph contains **{len(modules)} physical modules** and "
        f"**{edge_count} direct production dependency edges**.",
        "",
        "For each row, the component name and representative public header form a",
        "minimal consumer example using the template below:",
        "",
        "```cmake",
        "set(SHARP_RUNTIME_COMPONENTS <Component>)",
        "set(SHARP_RUNTIME_BUILD_TESTS OFF CACHE BOOL \"\" FORCE)",
        "add_subdirectory(sharp-runtime)",
        "target_link_libraries(MyApp PRIVATE SharpRuntime::<Component>)",
        "```",
        "",
        "The corresponding source includes the row's representative header. Consumers",
        "request only public dependencies; private and test-only dependencies are shown",
        "for maintainers and are not part of the consumer include surface.",
        "",
        "## Physical components",
        "",
        "| Component | Owner | Kind | Public dependencies | Private dependencies | Test-only dependencies | External/platform dependency | Representative public header |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for module in modules:
        lines.append(
            "| "
            f"`{module.name}` | `modules/{module.directory}` | "
            f"{module.module_type.lower()} | "
            f"{_format_items(module.public_dependencies)} | "
            f"{_format_items(module.private_dependencies)} | "
            f"{_format_items(module.test_dependencies)} | "
            f"{EXTERNAL_DEPENDENCIES.get(module.name, '—')} | "
            f"`{_representative_header(root / 'modules' / module.directory / 'include')}` |"
        )

    lines.extend(
        [
            "",
            "## Compatibility components",
            "",
            "Compatibility components preserve broad historical surfaces. New code should",
            "prefer the narrow physical component from the table above.",
            "",
            "| Component | Owner | Kind | Direct dependencies | Representative public header |",
            "|---|---|---|---|---|",
        ]
    )
    for component in compatibility:
        owner = (
            f"`modules/{component.owner}`"
            if component.owner != "CMake aggregate"
            else component.owner
        )
        lines.append(
            "| "
            f"`{component.name}` | {owner} | {component.component_type} | "
            f"{_format_items(component.dependencies)} | "
            f"`{_representative_header(component.include_directory)}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="Sharp Runtime repository root",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating an out-of-date catalogue",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()
    output_path = root / OUTPUT_PATH
    try:
        rendered = _render(root)
    except (OSError, ValueError) as error:
        print(f"FAIL: cannot generate component catalogue: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != rendered:
            print(
                "FAIL: docs/ComponentCatalog.md is out of date; run "
                "python3 scripts/generate_component_catalog.py",
                file=sys.stderr,
            )
            return 1
        print("OK: generated component catalogue is current")
        return 0

    output_path.write_text(rendered, encoding="utf-8")
    print(f"Updated {output_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
