// SPDX-License-Identifier: MIT
// Copyright (c) Robert Vokac and contributors
// Portions based on .NET runtime API (MIT License, Copyright .NET Foundation and Contributors)
// Additional tests for DivideByZeroException, DuplicateWaitObjectException,
// EntryPointNotFoundException, BadImageFormatException, MemberAccessException
// (basic DefaultCtor_WhatNotEmpty, MessageCtor_WhatContainsMessage, IsA_Exception
//  are already generated by EXCEPT_SIMPLE in ExceptionRemainingTests.cpp)
#include <gtest/gtest.h>
#include "System/DivideByZeroException.hpp"
#include "System/DuplicateWaitObjectException.hpp"
#include "System/EntryPointNotFoundException.hpp"
#include "System/BadImageFormatException.hpp"
#include "System/MemberAccessException.hpp"

// ---------------------------------------------------------------------------
// DivideByZeroException
// ---------------------------------------------------------------------------
TEST(DivideByZeroExceptionNewTests, InnerExceptionCtor_ContainsBoth) {
    std::runtime_error inner("cause");
    System::DivideByZeroException e("div fail", inner);
    std::string msg(e.what());
    EXPECT_NE(msg.find("div fail"), std::string::npos);
    EXPECT_NE(msg.find("cause"), std::string::npos);
}
TEST(DivideByZeroExceptionNewTests, IsArithmeticException) {
    System::DivideByZeroException e;
    EXPECT_NE(dynamic_cast<System::ArithmeticException*>(&e), nullptr);
}
TEST(DivideByZeroExceptionNewTests, DefaultMsg_ContainsDivide) {
    System::DivideByZeroException e;
    EXPECT_NE(std::string(e.what()).find("zero"), std::string::npos);
}

// ---------------------------------------------------------------------------
// DuplicateWaitObjectException
// ---------------------------------------------------------------------------
TEST(DuplicateWaitObjectExceptionNewTests, ParamNameCtor_IsArgumentException) {
    System::DuplicateWaitObjectException e("items");
    EXPECT_NE(dynamic_cast<System::ArgumentException*>(&e), nullptr);
}
TEST(DuplicateWaitObjectExceptionNewTests, ParamNameMessageCtor_StoresMessage) {
    System::DuplicateWaitObjectException e("items", "custom msg");
    EXPECT_NE(std::string(e.what()).find("custom msg"), std::string::npos);
}

// ---------------------------------------------------------------------------
// EntryPointNotFoundException
// ---------------------------------------------------------------------------
TEST(EntryPointNotFoundExceptionNewTests, InnerExceptionCtor_ContainsBoth) {
    std::runtime_error inner("dl error");
    System::EntryPointNotFoundException e("no entry", inner);
    std::string msg(e.what());
    EXPECT_NE(msg.find("no entry"), std::string::npos);
    EXPECT_NE(msg.find("dl error"), std::string::npos);
}

// ---------------------------------------------------------------------------
// BadImageFormatException
// ---------------------------------------------------------------------------
TEST(BadImageFormatExceptionNewTests, InnerExceptionCtor_ContainsBoth) {
    std::runtime_error inner("io err");
    System::BadImageFormatException e("bad dll", inner);
    std::string msg(e.what());
    EXPECT_NE(msg.find("bad dll"), std::string::npos);
    EXPECT_NE(msg.find("io err"), std::string::npos);
}
TEST(BadImageFormatExceptionNewTests, DefaultMsg_ContainsFormat) {
    System::BadImageFormatException e;
    EXPECT_NE(std::string(e.what()).find("Format"), std::string::npos);
}

// ---------------------------------------------------------------------------
// MemberAccessException
// ---------------------------------------------------------------------------
TEST(MemberAccessExceptionNewTests, DefaultMsg_NotEmpty) {
    System::MemberAccessException e;
    EXPECT_FALSE(std::string(e.what()).empty());
}
TEST(MemberAccessExceptionNewTests, StringCtor_MessageStored) {
    System::MemberAccessException e("no access");
    EXPECT_EQ(std::string(e.what()), "no access");
}
