# SPDX-License-Identifier: MIT
# Copyright (c) Robert Vokac and contributors

include_guard(GLOBAL)

file(GLOB SHARP_RUNTIME_CORE_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/*.cpp"
)
list(APPEND SHARP_RUNTIME_CORE_SOURCES
    "${SHARP_RUNTIME_ROOT}/src/System/IO/IOException.cpp"
    "${SHARP_RUNTIME_ROOT}/src/System/IO/DirectoryNotFoundException.cpp"
)

file(GLOB SHARP_RUNTIME_DIAGNOSTICS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Diagnostics/*.cpp"
)
file(GLOB SHARP_RUNTIME_GLOBALIZATION_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Globalization/*.cpp"
)
file(GLOB SHARP_RUNTIME_NUMERICS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Numerics/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_RUNTIME_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Runtime/*.cpp"
)

file(GLOB SHARP_RUNTIME_TEXT_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Text/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_TEXT_JSON_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Text/Json/*.cpp"
)

file(GLOB SHARP_RUNTIME_THREADING_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Threading/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_THREADING_TASKS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Threading/Tasks/*.cpp"
)
file(GLOB SHARP_RUNTIME_TIMERS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Timers/*.cpp"
)

file(GLOB SHARP_RUNTIME_IO_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/IO/*.cpp"
)
list(REMOVE_ITEM SHARP_RUNTIME_IO_SOURCES
    "${SHARP_RUNTIME_ROOT}/src/System/IO/IOException.cpp"
    "${SHARP_RUNTIME_ROOT}/src/System/IO/DirectoryNotFoundException.cpp"
)
file(GLOB SHARP_RUNTIME_IO_COMPRESSION_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/IO/Compression/*.cpp"
)
file(GLOB SHARP_RUNTIME_IO_COMPRESSION_ZIP_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/IO/Compression/Zip*.cpp"
)
list(REMOVE_ITEM SHARP_RUNTIME_IO_COMPRESSION_SOURCES
    ${SHARP_RUNTIME_IO_COMPRESSION_ZIP_SOURCES}
)
file(GLOB_RECURSE SHARP_RUNTIME_IO_HASHING_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/IO/Hashing/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_IO_ISOLATED_STORAGE_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/IO/IsolatedStorage/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_STORAGE_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/SharpRuntime/Storage/*.cpp"
)

file(GLOB SHARP_RUNTIME_NET_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/*.cpp"
)
file(GLOB SHARP_RUNTIME_NET_HTTP_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/Http/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_NET_HTTP_HEADERS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/Http/Headers/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_NET_MIME_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/Mime/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_NET_NETWORK_INFORMATION_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/NetworkInformation/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_NET_SOCKETS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/Sockets/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_NET_WEBSOCKETS_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Net/WebSockets/*.cpp"
)

file(GLOB_RECURSE SHARP_RUNTIME_CRYPTOGRAPHY_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Security/Cryptography/*.cpp"
)
set(SHARP_RUNTIME_CRYPTOGRAPHY_RANDOM_SOURCES
    "${SHARP_RUNTIME_ROOT}/src/System/Security/Cryptography/RandomNumberGenerator.cpp"
)
list(REMOVE_ITEM SHARP_RUNTIME_CRYPTOGRAPHY_SOURCES
    ${SHARP_RUNTIME_CRYPTOGRAPHY_RANDOM_SOURCES}
)

file(GLOB SHARP_RUNTIME_XML_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Xml/*.cpp"
)
file(GLOB_RECURSE SHARP_RUNTIME_XML_XPATH_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Xml/XPath/*.cpp"
)
list(APPEND SHARP_RUNTIME_XML_SOURCES
    ${SHARP_RUNTIME_XML_XPATH_SOURCES}
)
file(GLOB_RECURSE SHARP_RUNTIME_XML_LINQ_SOURCES CONFIGURE_DEPENDS
    "${SHARP_RUNTIME_ROOT}/src/System/Xml/Linq/*.cpp"
)
